### ISSUE TITLE
angular cli build error

### ISSUE THREAD

**Issue by nasserghiasi** [UncommonConcept/ngx-toggle-switch#3]
ERROR in : Unexpected value 'UiSwitchModule in /project/node_modules/ngx-toggle-switch/dist/index.d.ts' imported by the module 'AppModule in /project/src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by nasserghiasi** [comment]
the main repository fixed this issue, please remove this fork.

**Comment by fahadbraveknight** [comment]
Having same issue. Please tell how to fix this.

**Comment by thecodeguru360** [comment]
Try to use this import statement

`import { UiSwitchModule } from 'ngx-toggle-switch/src'`

**Comment by codinronan** [comment]
I have brought this repo up to date with the upstream repo, so it brings in all the AOT, NG5, bugfix goodies. Please note, the new version builds on Angular 5, hopefully you can update.

By the way the new version is now also published to NPM:
https://www.npmjs.com/package/ngx-toggle-switch
